### PR TITLE
Issues/29

### PR DESCRIPTION
**Pull request by LemurPwned**
This references #29 
Fixes:
- formatting (applies the settings menu selected options - not all are available now though)
- redrawing (faster and is corretly looping now)

### CODE REVIEW

**Comment by LemurPwned** [comment]
Agreed, fixes in progress

**Comment by LemurPwned** [comment]
This set of commits shoudl fix all the bugs in the #29. Let me know if it works for you.

**Comment by pawelkulig1** [comment]
Now it's better, few bugs still exists, maybe partial reason for that is my issue with resizing panes. I'm sure not 100% but I will accept it for now, but do not mark it as resolved.

**Comment by LemurPwned** [comment]
Can you specify what issue with reisizng panes? In case of 2d graph there is a resizing problem if not all of available widgets are selected

**Comment by pawelkulig1** [comment]
Yes that one.

**Comment by pawelkulig1** [comment]
Something is wrong with this merge could you please push your changes again? I can't resolve this issue. Or maybe you could merge that into master, because git desn't want to cooperate.

**Pull request merged**
